# Generated by Django 5.2.7 on 2025-11-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='drfpost',
            options={'ordering': ['-uploaded']},
        ),
        migrations.AddField(
            model_name='drfpost',
            name='cover',
            field=models.ImageField(blank=True, help_text='Upload cover buku (JPG, PNG, max 5MB)', null=True, upload_to='book_covers/'),
        ),
        migrations.AlterField(
            model_name='drfpost',
            name='rating',
            field=models.CharField(choices=[('excellent', 'Excellent'), ('average', 'Average'), ('bad', 'Bad')], default='average', max_length=50),
        ),
    ]
